name: size
description: A simple plugin that can display disk size on desktop.
version: 1.0.4
repository: https://github.com/Clashkid155/size
issue_tracker: https://github.com/Clashkid155/size/issues
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'
  flutter: '>=1.20.0 '
flutter:
  plugin:
    platforms:
      linux:
        pluginClass: SizePlugin
      windows:
        pluginClass: SizePlugin

dependencies:
  ffi: ^1.1.2
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
